(logai-py310) PS D:\logai-main\logai> $env:ES_USERNAME="cg722v"; $env:ES_PASSWORD="RGStatus2025"; python .\elastic_wrapper.py
Traceback (most recent call last):
  File "D:\logai-main\logai\elastic_wrapper.py", line 99, in <module>
    .transform(lambda x: x.rolling(window=window_size).count())
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\groupby\generic.py", line 517, in transform
    return self._transform(
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\groupby\groupby.py", line 2027, in _transform
    return self._transform_general(func, engine, engine_kwargs, *args, **kwargs)
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\groupby\generic.py", line 557, in _transform_general
    res = func(group, *args, **kwargs)
  File "D:\logai-main\logai\elastic_wrapper.py", line 99, in <lambda>
    .transform(lambda x: x.rolling(window=window_size).count())
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\generic.py", line 12599, in rolling
    return Rolling(
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\window\rolling.py", line 170, in __init__
    self._validate()
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\window\rolling.py", line 1877, in _validate
    self._validate_datetimelike_monotonic()
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\window\rolling.py", line 1922, in _validate_datetimelike_monotonic
    self._raise_monotonic_error("values must not have NaT")
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\window\rolling.py", line 1933, in _raise_monotonic_error
    raise ValueError(f"{on} {msg}")
ValueError: index values must not have NaT
